language: node_js
node_js:
- '0.12'
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
  webhooks:
    urls:
    - https://whispering-sands-84094.herokuapp.com/telegram-bot/travisci/37798333
    on_start: always
deploy:
  provider: npm
  email: darkrodry@gmail.com
  api_key:
    secure: YyPORKEWpSlHg0R9UONEhGy+oczKZqROmHZaH7ZkuJeq9TgO1vzQduqPbnZEQNt4Gz+erc87eoiAKHsgoAzmSN/l7qnx8KCEATPkY5lHRIceem1uSBxSYo8gz5wN1lMu4A1ePEu4iDzH1Kvx7kN7AHXaUG3M0wbU89XQZ/DyOTL4/ONe0cRQyUJJ/Wfz0nL6Si6qlVSrqqAUJMrhwlE45lQLLkyG8M5Z2rr6MbnqmQr8rbVmxhaRDHpJt3awN7pnprYZX2PebfD9THUFlzPkrb/cs+d6o8RXw3qBBrlpF0/o9pW177NPc5OGDnSMTD58doIynSH7DtvjQp/pUPRFWKE2MTtknqD9y5d0jj98lX6kqVYJWk6jsAllkX3Nw/YalTEVdnu8k1KQRwif77d0urY5tU9NjUczKmsalC8xwBXA/0Y2K0YVvAAG+wNitVHnWWMzTsxewtrIeccRAu94l9iAIcNo9CwSOgvs6tKbFXrt9zK6z0b/IzNyzi+LJoWOAatPHAC4Dr4tHH76MkP7/edgCBAQskZVJQyBZd2oVAY7FekBTwjROsqJH6V6D2zcJ9E4QpGEylzeoX7E8UBNSBkrzis9qnaN+A5FgQIFOOUrQLsAufi382wNHmSbULcJRK15K1/wVOIGerEflj13z7JwhKVIW7BaDY4Wg6kCdfk=
  on:
    tags: true
    repo: darkrodry/hubot-chuck-norris-icndb
