language: node_js
node_js:
- '0.12'
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
  webhooks:
    urls:
      - https://whispering-sands-84094.herokuapp.com/telegram-bot/travisci/37798333
    on_start: always
deploy:
  provider: npm
  email: "darkrodry@gmail.com"
  api_key:
    secure: H6nViLUg50f5JQWHrSb6Bsp0bxWu3PnxbdtQJHWmSYcEMR62LLBhw43i6SCh29t0GzamuwJa5FLRfIjZlvljES9nLk3aLdRPAaXGh4Z37DkJGYquQ10Hl+JTzst/fV3yY73sao4jWW4kPHkK4IQtIeWTbJFShQco/5r4FmNHEFM0smJEnQ1Eh2y2GeGbaIN6v91nSoq94z9/TWxTQ4xsWB5PKrx1/0ah0XSYunU0rzRukOTnxVwrtl6uSoPT5eE8ImxIle2T6stmILaHL3RctRVlooekIbPLK3sxp7v2u3QxwEp+MPjougn4lENcc0IiQAcXbxBsWQwTjZy3t45nwQlXNgYqVeZjOUH4UQAuYtE53NpYsNjQC9Fa9ntVyfnmaxzp1nJJcMh6oeQpLVgrIeHd4CZ611TYP/CnpR6YrUfgd1KQit7jqPvllXhgu3I9AkoeCvhR30sVCeXiJScJ2rFER1+hegUAq4WO5QoD2iu+UvtbWUTHUyM7sm8xEnFvFHqrCFkgZt8lf8J8fdj+dJC05kQ+S/V1464UaVgD6lVnnGKEvsTX1G5DaSJD9Yy6RW1MTjbH7Ybm+tmQvAZ/JoIMiI5jagopD/nec4tzNjH38uNXngvr+0zE1LF4gZfRXido5gy2y1uF/BXGeuqKxOEWr6/AnwhoEhN/IiXskBM=
  on:
    tags: true
